export const SAMPLE_ITEMS = [
  {
    id: 'sample-haru-p02-l020',
    examId: 'WEP26SP4W4-F',
    studentName: 'Haru',
    grade: 'G1',
    pageNum: 2,
    lineNum: 20,
    taskType: 'F',
    imageUrl: '',
    pageImageUrl: '',
    appleText: 'do bore mark So you will fell bad',
    qwenText: 'do home work So you will feel bad.',
    loraText: 'do home work So you will fell bad.',
    currentText: 'do home work So you will fell bad.',
    confidence: 0.58,
    reviewRequired: true,
    reasons: ['engine_disagreement', 'possible_word_substitution'],
    teacherScore: { structure: '', content: '', mechanics: '' },
  },
  {
    id: 'sample-otis-p05-l011',
    examId: 'WEP26SP4W4-F',
    studentName: 'Otis',
    grade: 'G2',
    pageNum: 5,
    lineNum: 11,
    taskType: 'F',
    imageUrl: '',
    pageImageUrl: '',
    appleText: 'City Birds live in city 5o there',
    qwenText: 'City Birds live in city so there',
    loraText: 'City Birds live in city so there',
    currentText: 'City Birds live in city so there',
    confidence: 0.91,
    reviewRequired: false,
    reasons: ['high_consensus'],
    teacherScore: { structure: '', content: '', mechanics: '' },
  },
  {
    id: 'sample-stella-essay',
    examId: 'WEP26SP4W4-F',
    studentName: 'Stella',
    grade: 'G5',
    pageNum: 7,
    lineNum: null,
    taskType: 'F',
    imageUrl: '',
    pageImageUrl: '',
    appleText: 'Ever thougut about birds living incities? Cities is a bad',
    qwenText: 'Ever thought about birds living in cities? Cities is a bad',
    loraText: 'Ever thought about birds living in cities? Cities is a bad',
    currentText: 'Ever thought about birds living in cities? Cities is a bad',
    confidence: 0.83,
    reviewRequired: true,
    reasons: ['teacher_score_anchor_needed'],
    teacherScore: { structure: 5, content: 4, mechanics: 4 },
  },
];
